---
title: "MA8701 Advanced methods in statistical inference and learning"
author: "Mette Langaas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
subtitle: 'Part 3: Ensembles. L14: Boosting'
bibliography: ../Part1/references.bib
nocite: |
  @casi, @ESL, @ISL,@Bagging,@Randomforest, @Ripley
format: 
  html: 
    toc: true
    code-fold: true
    toc-location: left
    toc-depth: 3
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    keep-tex: true
  beamer:
    incremental: false
    aspectratio: 43
    navigation: frame
editor: 
  markdown: 
    wrap: 72
---

```{r}
#| eval: true
#| echo: false
#| warning: false
suppressPackageStartupMessages(library(knitr))
knitr::opts_chunk$set(echo = FALSE, message=FALSE,warning = FALSE, error = FALSE)
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(rpart))
suppressPackageStartupMessages(library(rpart.plot))
suppressPackageStartupMessages(library(randomForest))
suppressPackageStartupMessages(library(DAAG))
suppressPackageStartupMessages(library(tree))
suppressPackageStartupMessages(library(MASS))
suppressPackageStartupMessages(library(GGally))
suppressPackageStartupMessages(library(corrplot))
suppressPackageStartupMessages(library(caret)) #for confusion matrices
suppressPackageStartupMessages(library(pROC)) #for ROC curves
suppressPackageStartupMessages(library(dplyr))
```

Course homepage: <https://wiki.math.ntnu.no/ma8701/2023v/start>

# Before we start

## Outline


---

## Literature

* [ESL] The Elements of Statistical Learning: Data Mining, Inference, and Prediction, Second Edition (Springer Series in Statistics, 2009) by Trevor Hastie, Robert Tibshirani, and Jerome Friedman. [Ebook](https://hastie.su.domains/ElemStatLearn/download.html). Chapter 10.1-10.6, 10.9, 10.10, 10.12, (10.13 later), 16.1-16.2

* Video by Berent Lunde (link on Bb), covering Chapter 10 (in particular 10.10) and the Chen and Guestrin paper.

* Chen, T., & Guestrin, C. (2016). XGBoost: A Scalable Tree Boosting System. In Proceedings of the 22nd ACM SIGKDD International Conference on Knowledge Discovery and Data Mining (pp. 785–794). New York, NY, USA: ACM. https://doi.org/10.1145/2939672.2939785. The mathematical notation is not in focus

# Timeline

1997: Freund and Schapire: AdaBoost.M1
1995: Breiman understand AdaBoost from different view
: Gradient boosting

# AdaBoost.M1
(10.1)
Algorithm 10.1: AdaBost.M1

Figure 2: stump, 244-node tress, AdaBoost.M1

# Forward Stagewise Additive Modelling with Exponential loss
(10.2-10.4)

Algorithm 10.2: Forward Stagewise Additive Modelling

# Boosting treees
(10.9)

# Regularization
(10.12)


# References

::: {#refs}
:::

